pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'pip install -r requirements.txt'
                }
            }
        stage('Test and Coverage') {
            steps {
                script {

                    def files = findFiles(glob: '**/test-*.py')
                    for (file in files) {
                        sh "coverage run --omit*/site-packages/*,*/dist-packages/* ${file}.path"

                        sh 'coverage report'
                    }

                    
                }

            }
            post {
                always {
                    script {
                        def test_reports_exist = fileExists 'test-reports'
                        if (test_reports_exist) {                        
                            junit 'test-reports/*.xml'
                        }

                        def api_test_reports_exist = fileExists 'api-test-reports'
                        if (api_test_reports_exist) {                        
                            junit 'api-test-reports/*.xml'
                        }
                    }
                }
            }
        }

        stage('Python Lint') {
            steps {
                script {
                    def all_py = findFiles(glob: '*.py')
                    for (i in all_py) {
                        sh "pylint-fail-under --fail_under 5.0 ${i}"
                    }
                    
                }
                
            }
        }

        stage('Zip Artifacts') {
            steps {
                script {
                    zip zipFile: 'app.zip', glob: '*.py'
                    archiveArtifacts artifacts: 'app.zip'
                }
            }
        }
    }
}
